---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Show UFW rules
  ansible.builtin.command: ufw status numbered
  when: releasy_server_firewall_show_rules
  changed_when: false

- name: Apply netplan
  ansible.builtin.command: netplan apply
  changed_when: true
