---
keycloak_enabled: false
keycloak_image: "keycloak/keycloak:26.4"
keycloak_container_name: "keycloak"
keycloak_http_port: 8080
keycloak_bind_address: ""
keycloak_data_dir: "/var/lib/keycloak"
keycloak_env_dir: "/etc/keycloak"
keycloak_env_file: "/etc/keycloak/keycloak.env"
keycloak_hostname: "auth.example.com"
keycloak_db_host: "{{ postgres_host }}"
keycloak_db_port: "{{ postgres_port }}"
keycloak_db_name: "keycloak"
keycloak_db_user: "keycloak"
keycloak_db_ssl_mode: "disable"
keycloak_proxy_headers: "xforwarded"
keycloak_http_enabled: true
keycloak_hostname_strict: true
keycloak_hostname_strict_https: true
keycloak_health_enabled: true
keycloak_metrics_enabled: false
keycloak_extra_env: []
keycloak_realm_import_enabled: false
keycloak_realm_import_source: "template"
keycloak_realm_import_src: ""
keycloak_realm_import_dest: "realm.json"
keycloak_start_args: []
keycloak_docker_dns: []
keycloak_realm_name: "releasy"
keycloak_portal_client_id: "releasy-portal"
keycloak_portal_client_secret: ""
keycloak_portal_root_url: "https://portal.example.com"
keycloak_portal_redirect_uris:
  - "{{ keycloak_portal_root_url }}/*"
keycloak_portal_web_origins:
  - "{{ keycloak_portal_root_url }}"
keycloak_admin_realm: "master"
keycloak_admin_base_url: "http://127.0.0.1:{{ keycloak_http_port }}"
keycloak_service_account_client_roles: []
keycloak_smtp_enabled: false
keycloak_smtp_host: ""
keycloak_smtp_port: 587
keycloak_smtp_starttls: true
keycloak_smtp_ssl: false
keycloak_smtp_auth_enabled: false
keycloak_smtp_user: ""
keycloak_smtp_password: ""
keycloak_smtp_from: ""
keycloak_smtp_from_display_name: ""
keycloak_smtp_reply_to: ""
keycloak_smtp_reply_to_display_name: ""
keycloak_smtp_envelope_from: ""
