# Encrypt this file with ansible-vault.
releasy_admin_api_key: "<set-me>"
releasy_api_key_pepper: "<set-me>"
releasy_registry_username: "<set-me>"
releasy_registry_password: "<set-me>"
releasy_database_url: "<set-me>"
releasy_artifact_access_key: "<set-me>"
releasy_artifact_secret_key: "<set-me>"
postgres_app_password: "<set-me>"
keycloak_admin_user: "<set-me>"
keycloak_admin_password: "<set-me>"
keycloak_db_password: "<set-me>"
tailscale_auth_key: "<set-me>"
