---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart keycloak instances
  ansible.builtin.systemd:
    name: "keycloak@{{ item }}"
    state: restarted
  loop: "{{ keycloak_instances | default([]) }}"
